### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by Crystal-RainSlide** [zhanghua000/vscodium-language-pack-zh-cn#1]
两个月没更新了，已经有地方断片了。

要不要配置 CI，自动合并和发布来自上游的更新？

**Comment by zhanghua000** [comment]
项目已经更新，以后项目的地址改变到 [这里](https://github.com/zhanghua000/vscode-loc) 这样直接从巨硬那里同步会简单一点。萌新对GitHub不熟练，还在慢慢研究这些东西，还望大佬海涵😂
